from typing import Any, overload, Protocol, Union

from src.modules.views.data_objects import VisitorData


class ViewableServiceProtocol(Protocol):

    @property
    def uow(self) -> Any: ...

    @property
    def cache(self) -> Any: ...

    @property
    def queue(self) -> Any: ...

    def _get_model_name(self) -> str: ...

    def _get_cache_key(self, obj_id: int) -> str: ...

    def _get_hll_key(self, obj_id: int) -> str: ...

    def _get_visitor_hash(self, visitor_data: VisitorData) -> str: ...

    @overload
    async def get_views(self, obj_id: int) -> int: ...

    @overload
    async def get_views(self, obj_id: list[int]) -> dict[int, int]: ...

    async def get_views(self, obj_id: Union[int, list[int]]) -> Union[int, dict[int, int]]: ...

    @overload
    async def increment_views(self, obj_id: int, visitor_data: VisitorData) -> None: ...

    @overload
    async def increment_views(self, obj_id: list[int], visitor_data: VisitorData) -> None: ...

    async def increment_views(self, obj_id: Union[int, list[int]], visitor_data: VisitorData) -> None: ...

    async def process_view_logs(self, payloads: list[dict[str, Any]]) -> None: ...

    @overload
    async def _enrich_with_views(self, items: Any) -> Any: ...

    @overload
    async def _enrich_with_views(self, items: list[Any]) -> list[Any]: ...

    async def _enrich_with_views(self, items: Any | list[Any]) -> Any | list[Any]: ...
