EVENTS_PATH = "/events"

EVENT_DETAILS_PATH = EVENTS_PATH + "/"
PRIVATE_EVENTS_PATH = EVENTS_PATH + "/my"
EVENT_CATEGORIES_PATH = EVENTS_PATH + "/categories"
EVENTS_INCREMENT_VIEWS_PATH = EVENTS_PATH + "/views"
